### ISSUE TITLE
Rex Media List Scrolling

### ISSUE THREAD

**Issue by killerpixel** [georgkaser/bgk_skin#7]
das skin ist echt gut, ich nutze es gern,
ich hab nur das gefühl, dass es bei REX MEDIALIST's das scrolling behindert.
ich fixe es zzt immer nur in der basic.css von redaxo mit select{overflow: scroll !important;}

**Comment by georgkaser** [comment]
Servus und danke für deine Info. Ich schau mir das an und fixe das. Ich arbeite auch schon an einer neuen Version, diese wird dann responsive sein und via Installer installierbar sein (wenn ichs hinkrieg :)) und die bgk_skin ersetzen. Nähere Infos dann hier. Beste Grüße, Georg.

**Comment by killerpixel** [comment]
Hey,

cool, danke für dein feedback,
kann ich dich irgendwie unterstützen?

Gruß, Ron

**Comment by georgkaser** [comment]
Ich hab den Fehler jetzt überprüft und keine Probleme mit den Selects festgestellt. Welcher Browser macht bei dir Probleme? Und was genau ist das Problem - ich konnte keinen Unterschied feststellen nach Einbau von select{overflow: scroll !important;}

**Comment by georgkaser** [comment]
Fehler gefunden :) Danke für deine Meldung!

**Comment by killerpixel** [comment]
Hi,
ach siehste, ich wollte noch zurückschreiben,
sorry :)
aber danke für den fix! :)

**Comment by georgkaser** [comment]
Gerne ;)
